#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : enable
#include "hitpayload.glsli"

layout(location = 0) rayPayloadEXT HitPayload payload;

layout(set=0,binding=0) uniform SceneParameters
{
  mat4 mtxView;
  mat4 mtxProj;
  mat4 mtxViewInv;
  mat4 mtxProjInv;
} sceneParams;

layout(set=0,binding=1) uniform accelerationStructureEXT topLevelAS;
layout(set=0,binding=2,rgba8) uniform image2D resultImage;


void main() {
  const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
  const vec2 screenPos = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
  vec2 d = screenPos * 2.0 - 1.0;

  // レイを飛ばす.
  vec4 origin = sceneParams.mtxViewInv * vec4(0, 0, 0, 1);
  vec4 target = sceneParams.mtxProjInv * vec4(d.x, -d.y, 1, 1);
  vec4 direction = sceneParams.mtxViewInv * vec4(target.xyz, 0);
  float tmin = 0.001, tmax = 10000.0;
  traceRayEXT(
    topLevelAS,
    gl_RayFlagsOpaqueEXT,
    0xff, // cullMask
    0,    // sbtRecordOffset
    1,    // sbtRecordStride
    0,    // missIndex
    origin.xyz, tmin, direction.xyz, tmax,
    0     // payload
  );

  // 結果をバッファに記録.
  vec3 finalColor = payload.color;
  imageStore(resultImage, ivec2(gl_LaunchIDEXT.xy), vec4(finalColor, 1.0));
}
