#version 450

#define THREAD_NUM 64
#define RADIUS 5

layout(set=0,binding=0,rgba8)
uniform readonly image2D srcImage;

layout(set=0,binding=1,rgba8)
uniform image2D dstImage;

const float weights[2*RADIUS+1] = {
  // sigma = 5
  0.0663416684,
  0.0794253945,
  0.0913609490,
  0.100969456,
  0.107213065,
  0.109378912,// 0
  0.107213065,
  0.100969456,
  0.0913609490,
  0.0794253945,
  0.0663416684,
};
shared vec3 sdata[THREAD_NUM + RADIUS*2];

ivec2 adjustPixelCoord(ivec2 coord, ivec2 imageDims)
{
  return clamp(coord, ivec2(0), imageDims-1);
}


void doFilter(ivec2 direction)
{
  uint invocationIndex = gl_LocalInvocationIndex;
  ivec2 current = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imageDims = imageSize(srcImage);

  sdata[invocationIndex + RADIUS] = imageLoad(srcImage, adjustPixelCoord(current, imageDims)).xyz;

  if(invocationIndex < RADIUS)
  {
    // Left or Upper
    ivec2 outerPixel = current - direction;
    sdata[invocationIndex] = imageLoad(srcImage, adjustPixelCoord(outerPixel, imageDims)).xyz;
  }
  if(invocationIndex >= THREAD_NUM - RADIUS)
  {
    // Right or Bottom
    ivec2 outerPixel = current + direction;
    sdata[invocationIndex + RADIUS*2] = imageLoad(srcImage, adjustPixelCoord(outerPixel, imageDims)).xyz;
  }
  barrier();

  vec3 result = vec3(0);
  for(int i=0;i<2*RADIUS+1;++i)
  {
    result += sdata[i+invocationIndex] * weights[i];
  }
  imageStore(dstImage, ivec2(gl_GlobalInvocationID.xy), vec4(result, 1)) ;
}

#ifdef USE_GAUSS_FILTER_H
layout(local_size_x=THREAD_NUM, local_size_y=1, local_size_z=1) in;
void main()
{
  doFilter(ivec2(RADIUS, 0));
}
#endif

#ifdef USE_GAUSS_FILTER_V
layout(local_size_x=1, local_size_y=THREAD_NUM, local_size_z=1) in;
void main()
{
  doFilter(ivec2(0, RADIUS));
}
#endif



#ifdef USE_STD_GAUSS_FILTER_H
layout(local_size_x=THREAD_NUM, local_size_y=1, local_size_z=1) in;
void main()
{
  ivec2 index = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imageDims = imageSize(srcImage);

  vec3 result = vec3(0);
  for(int i = -RADIUS; i <= RADIUS; ++i)
  {
    ivec2 current = index + ivec2(i, 0);
    // 画像サイズを超えないようクランプ処理.
    current = adjustPixelCoord(current, imageDims);
    
    // 係数を掛けて累積していく.
    vec3 color = imageLoad(srcImage, current).xyz;
    float w = weights[i+RADIUS];
    result += color * w;
  }
  imageStore( dstImage, ivec2(index), vec4(result, 1));
}
#endif

#ifdef USE_STD_GAUSS_FILTER_V
layout(local_size_x=1, local_size_y=THREAD_NUM, local_size_z=1) in;
void main()
{
  ivec2 index = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imageDims = imageSize(srcImage);

  vec3 result = vec3(0);
  for(int i = -RADIUS; i <= RADIUS; ++i)
  {
    ivec2 current = index + ivec2(0, i);
    // 画像サイズを超えないようクランプ処理.
    current = adjustPixelCoord(current, imageDims);
    
    // 係数を掛けて累積していく.
    vec3 color = imageLoad(srcImage, current).xyz;
    float w = weights[i+RADIUS];
    result += color * w;
  }
  imageStore( dstImage, ivec2(index), vec4(result, 1));
}
#endif

